FROM gyselroth/tubee:php7.2-fpm-v8js

ENV TUBEE_ENCRYPTION_KEY 314004007129e4d0bfbc36d0242d33ffadc798a8a55a307ce245392d91f2474efd7ce229af7ea3ed08ddbff1010678ac71050572856abdc54b851665d3a5afbd3c77dda953d5cfa066112b61aca7e04f0f71224db3c89c2e178f4a361b49799e3a32079d

RUN mkdir -p /usr/share/man/man1/ && echo TLS_REQCERT never > /etc/ldap/ldap.conf

RUN apt-get update && apt-get install -y \
  libldb-dev \
  libldap2-dev \
  libxml2-dev \
  libcurl4-openssl-dev \
  libssl-dev \
  libzip-dev \
  libicu-dev \
  libreoffice \
  libsmbclient-dev \
  gnupg \
  strace \
  apt-transport-https \
  libmagickwand-dev \
  unixodbc-dev \
  build-essential \
  curl \
  git \
  chrpath \
  python \
  libglib2.0-dev \
  ca-certificates-java \
  && rm -rf /var/lib/apt/lists/*

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
    && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y unixodbc unixodbc-dev msodbcsql17 wget dialog  \
    && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.a /usr/lib/ \
    && ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/ \
    && wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u11_amd64.deb \
    && dpkg -i *.deb

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y locales \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen en_US.UTF-8 \
    && dpkg-reconfigure locales \
    && /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN ln -s /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/libldap.so
RUN docker-php-ext-install ldap xml opcache curl zip intl sockets pcntl sysvmsg mysqli

RUN pecl install mongodb \
    && pecl install apcu \
    && pecl install imagick \
    && pecl install smbclient \
    && pecl install sqlsrv \
    && pecl install pdo_sqlsrv \
    && docker-php-ext-enable mongodb apcu imagick smbclient pcntl sqlsrv pdo_sqlsrv mysqli

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug \
    && echo "xdebug.overload_var_dump=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && ln -s /srv/www/tubee/config/php.ini /usr/local/etc/php/conf.d/zz-custom.ini

RUN apt-get update && apt-get --no-install-recommends install -y nginx make rsync gnupg smbclient

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php composer-setup.php --filename=composer --install-dir=/usr/bin \
 && php -r "unlink('composer-setup.php');"

RUN mkdir /etc/ssl/tubee \
  && openssl genrsa -des3 -passout pass:x12345 -out server.pass.key 2048 \
  && openssl rsa -passin pass:x12345 -in server.pass.key -out key.pem \
  && rm server.pass.key \
  && openssl req -new -key key.pem -out server.csr -subj "/C=CH//L=Zurich/O=Balloon/CN=tubee.local" \
  && openssl x509 -req -days 365 -in server.csr -signkey key.pem -out chain.pem \
  && rm server.csr \
  && mv key.pem /etc/ssl/tubee/ \
  && mv chain.pem /etc/ssl/tubee/

COPY packaging/docker-dev/nginx.conf /etc/nginx/conf.d/tubee.conf

RUN echo "pm.max_children = 500" >> /usr/local/etc/php-fpm.d/www.conf.default \
  && echo "pm.max_children = 500" >> /usr/local/etc/php-fpm.d/www.conf

EXPOSE 80 443 9000

CMD make -C /srv/www/tubee deps; \
  php /srv/www/tubee/src/cgi-bin/cli.php upgrade -i; \
  service nginx start && php-fpm
