#!/bin/bash

echo "create symlinks and log folder"
if [ ! -d /var/log/tubee ]; then
  mkdir /var/log/tubee
fi

if [ ! -h /usr/share/tubee/config ]; then
    ln -s /etc/tubee /usr/share/tubee/config
fi

if [ ! -h /usr/share/tubee/log ]; then
    ln -s /var/log/tubee /usr/share/tubee/log
fi

if [ ! -h /usr/bin/tubeecli ]; then
    ln -s /usr/share/tubee/bin/console/tubeecli /usr/bin/tubeecli
fi

if [[ ! -f /etc/systemd/system/tubee-jobs.service && -d /etc/systemd/system ]]; then
    cp /usr/share/tubee/scripts/tubee-jobs.service.systemd /etc/systemd/system/tubee-jobs.service
fi

if [[ ! -f /etc/init/tubee-jobs.conf && -d /etc/init ]]; then
    cp /usr/share/tubee/scripts/tubee-jobs.service.upstart /etc/init/tubee-jobs.conf
fi

echo "create admin user"
/usr/bin/tubeecli upgrade -vvv
chown -R www-data. /var/log/tubee

echo "create systemctl service"
systemctl enable tubee-jobs.service 2> /dev/null

echo "restart tubee-jobs service"
if service --status-all | grep -Fq 'tubee-jobs'; then
  service tubee-jobs restart
fi

if [ ! -d /etc/ssl/tubee ]; then
  mkdir /etc/ssl/tubee
fi

if [[ ! -f /etc/ssl/tubee/key.pem && ! -f /etc/ssl/tubee/chain.pem ]]; then
  openssl genrsa -des3 -passout pass:tubee -out server.pass.key 2048
  openssl rsa -passin pass:tubee -in server.pass.key -out key.pem
  rm server.pass.key
  openssl req -new -key key.pem -out server.csr -subj "/C=CH/L=Zurich/O=Tubee/CN=tubee.local"
  openssl x509 -req -days 365 -in server.csr -signkey key.pem -out chain.pem
  rm server.csr
  mv key.pem /etc/ssl/tubee
  mv chain.pem /etc/ssl/tubee
fi

if [ ! -f /etc/nginx/conf.d/tubee.conf ]; then
  cp /usr/share/tubee/nginx/nginx.conf /etc/nginx/conf.d/tubee.conf
fi

service nginx restart

